# Generated by Django 5.0.1 on 2024-01-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Category Name')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='category_photos/', verbose_name='Category Photo')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
