# Generated by Django 5.0.1 on 2024-01-31 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='cotton', max_length=255, verbose_name='brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='smalldescription',
            field=models.TextField(blank=True, default='Women Self Design Pure Cotton A-line Kurta  (Blue)', null=True, verbose_name='small Product Description'),
        ),
    ]
