# Generated by Django 5.0.1 on 2024-01-31 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_product_brand_product_smalldescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=255, verbose_name='brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='smalldescription',
            field=models.TextField(blank=True, null=True, verbose_name='small Product Description'),
        ),
    ]
