# Generated by Django 5.0.1 on 2024-03-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pincode',
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='Default City', max_length=111),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='Default City', max_length=90),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(default='Default City', max_length=111),
        ),
        migrations.AddField(
            model_name='order',
            name='zip_code',
            field=models.CharField(default='Default City', max_length=111),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(default='Default City', max_length=111),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.CharField(default='Default City', max_length=111),
        ),
    ]
