# Generated by Django 5.0.1 on 2024-03-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_order_fullname_remove_order_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=111),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=111),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.CharField(max_length=111),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(max_length=111),
        ),
        migrations.AlterField(
            model_name='order',
            name='zip_code',
            field=models.CharField(max_length=111),
        ),
    ]
